"""Structured, reproducible assessment of a scenario.

This is the layer that answers the user's three questions about any scenario —
*what are the risks, which provisions apply (and why), and what should we do* —
and does so **reproducibly**.

Reproducibility is by design, via a hard split:

- **Deterministic core** (risks, primary provisions, related cross-framework
  provisions) is computed by code from a single retrieval pass over a fixed data
  store. Same scenario + same store + same retriever ⇒ identical core, every run.
- **LLM narrative** (the prose "why" and the recommended mitigants) is *labeled*
  as model-generated and runs at ``temperature=0`` with a fixed seed for
  best-effort reproducibility. It only ever narrates over the **exact same
  retrieved provisions** as the deterministic core — it cannot introduce new
  provisions or mappings.

So the facts a governance reviewer relies on are stable and auditable; only the
wording of the explanation can drift.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from .config import RegulusConfig
from .graph_lookup import GraphLookupResult, RegulusGraphLookup
from .interpret import Interpretation, RegulusInterpreter


@dataclass
class PrimaryProvision:
    citation: str
    framework: str
    score: float
    snippet: str
    risks: List[str] = field(default_factory=list)


@dataclass
class RelatedProvision:
    citation: str
    framework: str
    relation: str
    source: str          # citation/provenance of the crosswalk mapping
    related_to: str      # the primary provision this crosswalk hangs off


@dataclass
class Assessment:
    """The full, reproducible assessment of one scenario."""

    scenario: str
    target_system: str
    top_k: int
    retriever: str
    generation_model: str
    # deterministic core -----------------------------------------------------
    risks: List[Tuple[str, List[str]]]          # (risk category, provisions that address it)
    primary: List[PrimaryProvision]             # top applicable provisions, ranked
    related: List[RelatedProvision]             # cited cross-framework provisions
    # labeled LLM narrative --------------------------------------------------
    interpretation: Optional[Interpretation] = None

    # ---- rendering --------------------------------------------------------
    def to_markdown(self) -> str:
        lines: List[str] = []
        lines.append(f"## Regulus assessment")
        lines.append(f"**System under review:** {self.target_system}")
        lines.append(f"**Scenario:** {self.scenario}\n")

        # 1) Risks
        lines.append("### 1. Risks in this scenario")
        if self.risks:
            for risk, provs in self.risks:
                addressed = ", ".join(provs) if provs else "—"
                lines.append(f"- **{risk}** — governed by: {addressed}")
        else:
            lines.append("- *(no risk categories mapped to the retrieved provisions)*")

        # 2) Top / related provisions
        lines.append("\n### 2. Applicable provisions")
        if self.primary:
            for i, p in enumerate(self.primary, 1):
                risks = f"  \n  _risks:_ {', '.join(p.risks)}" if p.risks else ""
                lines.append(f"{i}. **{p.citation}** ({p.framework}) — relevance {p.score:.3f}{risks}")
        else:
            lines.append("- *(nothing retrieved)*")
        if self.related:
            lines.append("\n**Related cross-framework provisions (cited crosswalks):**")
            for rel in self.related:
                lines.append(
                    f"- **{rel.citation}** ({rel.framework}) — _{rel.relation}_ of {rel.related_to} "
                    f"[source: {rel.source or 'curated'}]"
                )

        # 3) LLM narrative (why + mitigants), clearly labeled
        lines.append("\n### 3. Interpretation & recommended mitigants")
        if self.interpretation is not None and self.interpretation.answer_markdown:
            lines.append(
                f"_Generated by {self.generation_model} at temperature 0 (labeled, best-effort "
                f"reproducible) over the exact provisions above._\n"
            )
            lines.append(self.interpretation.answer_markdown)
        elif self.interpretation is not None:
            lines.append(f"_LLM narrative not generated: {self.interpretation.note}._")
            lines.append(
                "\nThe deterministic core above (risks, applicable and related provisions) is complete "
                "and reproducible without the LLM."
            )
        else:
            lines.append("_(LLM narrative disabled.)_")

        # reproducibility footer
        lines.append(
            f"\n---\n_Reproducibility: the risks and provisions above are computed by code from a single "
            f"retrieval pass (retriever: **{self.retriever}**, top_k={self.top_k}) over a fixed data store — "
            f"identical on every run for the same scenario. Only the wording of section 3 may vary._"
        )
        return "\n".join(lines)


def _aggregate_risks(results: List[GraphLookupResult]) -> List[Tuple[str, List[str]]]:
    """Map each risk category to the retrieved provisions that address it.

    Ordered by how many provisions address the risk (descending), then name — a
    deterministic ordering independent of dict insertion.
    """
    by_risk: Dict[str, List[str]] = {}
    for r in results:
        for risk in r.risks:
            by_risk.setdefault(risk, [])
            if r.provision.citation() not in by_risk[risk]:
                by_risk[risk].append(r.provision.citation())
    return sorted(by_risk.items(), key=lambda kv: (-len(kv[1]), kv[0]))


def assess(
    graph_lookup: RegulusGraphLookup,
    scenario: str,
    top_k: int = 5,
    target_system: str = "",
    interpreter: Optional[RegulusInterpreter] = None,
    config: Optional[RegulusConfig] = None,
    with_llm: bool = True,
) -> Assessment:
    """Produce a reproducible :class:`Assessment` for ``scenario``.

    One retrieval pass feeds both the deterministic core and (optionally) the LLM
    narrative, guaranteeing they describe the same provisions.
    """
    cfg = config or graph_lookup.config
    results = graph_lookup.search(scenario, top_k=top_k)

    primary = [
        PrimaryProvision(
            citation=r.provision.citation(),
            framework=r.provision.framework_name,
            score=round(r.score, 3),
            snippet=r.snippet.strip()[:300],
            risks=r.risks,
        )
        for r in results
    ]
    related: List[RelatedProvision] = []
    seen = set()
    for r in results:
        for cx in r.crosswalks:
            key = (cx.provision.citation(), r.provision.citation())
            if key in seen:
                continue
            seen.add(key)
            related.append(
                RelatedProvision(
                    citation=cx.provision.citation(),
                    framework=cx.provision.framework_name,
                    relation=cx.relation,
                    source=cx.source,
                    related_to=r.provision.citation(),
                )
            )

    interpretation: Optional[Interpretation] = None
    if with_llm:
        interp = interpreter or RegulusInterpreter(graph_lookup, cfg, target_system=target_system)
        # Reuse the SAME retrieved results so the narrative can't drift from the core.
        interpretation = interp.interpret_results(scenario, results)

    return Assessment(
        scenario=scenario,
        target_system=target_system or "(not specified)",
        top_k=top_k,
        retriever=graph_lookup.lookup.retriever,
        generation_model=cfg.openai_generation_model,
        risks=_aggregate_risks(results),
        primary=primary,
        related=related,
        interpretation=interpretation,
    )
